# Generated by Django 2.0.3 on 2018-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecheck', '0002_sitecheck_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecheck',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='json_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
